import Head from 'next/head'

import { Inter } from '@next/font/google'
// import Navbar from "./comp/nav";
// import Header from "./comp/Header"
// import Subscript from "./comp/subscript"
// import Footer from "./comp/footer"
import Login from "./comp/login"

import Signup from "./comp/signup"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* <Navbar />
        <Header />
        <Subscript />
        <Footer /> */}
        <Signup/>
        {/* <Login/> */}

      

    </>
  )
}
